# This is a basic workflow to help you get started with Actions

name: SR-Linu CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Install containerlab
        run: sudo bash -c "$(curl -sL https://get.containerlab.dev)"

      - name: Check clab version
        run: clab version
  
      - name: Get topology file
        run: wget https://raw.githubusercontent.com/srl-labs/containerlab/main/lab-examples/srl02/srl02.clab.yml

      - name: Git clone
        run: git clone https://github.com/saogawa/CICD.git

      - name: Deploy the clab
        run: |
          ls -alt
          sudo clab deploy
          
      - name: Check srl1 version
        run: |
          docker exec -it client1 srl1 show version

      - name: Check srl2 version
        run: |
          docker exec -it client1 srl2 show version

      - name: Check LLDP stataus
        run: |
          docker exec -it client1 srl1 show system lldp neighbor
          docker exec -it client2 srl1 show system lldp neighbor
